language: csharp
solution: GKCommunicator.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./GKCommunicator.sln

script:
  - msbuild /p:Configuration=Debug /p:CIMode=true /p:MonoCS=true ./GKCommunicator.sln /p:TargetFrameworkVersion=v4.5
  - nunit-console ./GKNetCore.Tests/bin/Debug/GKNetCore.Tests.dll
