version: 0.1.45.{build}

pull_requests:
  do_not_increment_build_number: true

environment:
  CIMode: true

configuration: Debug

platform: Any CPU

before_build:
  - nuget restore
  - choco install opencover.portable
  - choco install codecov

build:
  project: GKCommunicator.sln
  verbosity: minimal

after_test:
  - OpenCover.Console.exe -register:user -target:"nunit-console-x86.exe" -targetargs:".\GKCommunicatorTests\bin\Debug\GKCommunicatorTests.dll /noxml" -output:".\coverage.xml" -filter:"+[*]* "
  - codecov -f "coverage.xml"
